### PR TITLE
Replaced 'CYColor' with a modern UIColor extension

### PR DESCRIPTION
**Pull request by ninjaprawn**
`CYColor` was a very confusing class, and it was in C++. Replacing this with a UIColor extension will add extra readability to the code.

### CODE REVIEW

**Review by kirb — CHANGES_REQUESTED** [review]
I'd say the methods should all end in `Color` to match convention, and maybe be more descript about their use. For instance, `cydia_purple` isn't purple and you wouldn't really know it's the commercial package cell text color.

**Comment by ninjaprawn** [comment]
Are you happy with the changes?

**Comment by JohnCoates** [comment]
@ninjaprawn you forgot to commit the changes to the Xcode project file, so the build is failing because Xcode doesn't know about `UIColor+CydiaColors.h/m`. Otherwise it looks good to me.

**Review by JohnCoates — APPROVED** [review]
Looks good!

**Pull request merged**
