### PR TITLE
Add shake to respring in HomeController

### PR DESCRIPTION
**Pull request by maximehip**
Can be a cool feature. I put it in my tweak CustomDia. We can it in all views.

### CODE REVIEW

**Comment by JohnCoates** [comment]
This adds shake to refresh instead of shake to respring. Is that what you meant to do?

**Comment by maximehip** [comment]
Yes that's it

**Comment by ninjaprawn** [comment]
How does this benefit the user? The only time we need to refresh (the data I suppose) is when we add a source and if we want to refresh for any changes. But the refresh is called when you open the app, so this seems kind of redundant as the chances of you reloading 5min after you open the app and there being an update are pretty small.

**Comment by maximehip** [comment]
That is true. I agree with you but its can bring a plus in the user experience

**Comment by kirb** [comment]
I wouldn’t want anything happening as a result of physical movement; it’s more likely that it’ll be (repeatedly) discovered by accident than intentionally activated. You could add a confirmation prompt like shake to undo does, but then the feature requires more effort than just tapping Changes &rarr; Refresh.

**Comment by JohnCoates** [comment]
I agree with @kirb, a confirmation would be ideal.

Once we get a settings panel added we can add a toggle for this feature, and maybe give the user the option to enable or disable it the first time it's activated.

**Review by JohnCoates — CHANGES_REQUESTED** [review]
Add an confirmation alert so the user knows what's happening and give them the option to cancel.

Instead of having it for just the home screen let's have it be app-wide.

**Comment by maximehip** [comment]
I think you're right

**Comment by JohnCoates** [comment]
@maximehip Since this pull request hasn't been updated with the changes requested, I'm closing it for now. Feel free to make the changes and resubmit.

**Pull request closed without merging**
